/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ASM;


import java.awt.HeadlessException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JosCongQuy
 */
public class QLNV extends javax.swing.JFrame {

    List<SinhVien> SV = new ArrayList<>();
    private DefaultTableModel mode = new DefaultTableModel();
    private int Index;

    public QLNV() {

        initComponents();
        this.setLocationRelativeTo(null);
        jTable1.setModel(mode);
        iniTable();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();
        jOptionPane2 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextNAME = new javax.swing.JTextField();
        jTextID = new javax.swing.JTextField();
        jTextSALARY = new javax.swing.JTextField();
        jTextYEAR_OLD = new javax.swing.JTextField();
        jTextEMAIL = new javax.swing.JTextField();
        BNTNEW = new javax.swing.JButton();
        BNTSAVE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabeltime = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BNTDELETE = new javax.swing.JButton();
        BNTFIND = new javax.swing.JButton();
        BNTOPEN = new javax.swing.JButton();
        BNTEXIT = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("QUẢN LÍ NHÂN VIÊN");

        jLabel3.setText("MÃ NHÂN VIÊN");

        jLabel4.setText("HỌ VÀ TÊN");

        jLabel5.setText("TUỔI");

        jLabel6.setText("EMAIL");

        jLabel7.setText("LƯƠNG");

        jTextNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNAMEActionPerformed(evt);
            }
        });

        jTextSALARY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSALARYActionPerformed(evt);
            }
        });

        jTextYEAR_OLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextYEAR_OLDActionPerformed(evt);
            }
        });

        jTextEMAIL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEMAILActionPerformed(evt);
            }
        });

        BNTNEW.setBackground(new java.awt.Color(255, 153, 153));
        BNTNEW.setForeground(new java.awt.Color(51, 0, 51));
        BNTNEW.setText("NEW");
        BNTNEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNTNEWActionPerformed(evt);
            }
        });

        BNTSAVE.setBackground(new java.awt.Color(255, 153, 153));
        BNTSAVE.setText("SAVE");
        BNTSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNTSAVEActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ", "HỌ VÀ TÊN", "TUỔI", "EMAIL", "LƯƠNG"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton2.setBackground(new java.awt.Color(51, 255, 0));
        jButton2.setText("|<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(102, 255, 0));
        jButton3.setText(">|");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 255, 51));
        jButton4.setText("<<");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(102, 255, 51));
        jButton5.setText(">>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabeltime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabeltime.setForeground(new java.awt.Color(255, 51, 51));
        jLabeltime.setText("hh:mm:ss aa");
        jLabeltime.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabeltimeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        BNTDELETE.setBackground(new java.awt.Color(255, 153, 153));
        BNTDELETE.setForeground(new java.awt.Color(51, 0, 51));
        BNTDELETE.setText("DELETE");
        BNTDELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNTDELETEActionPerformed(evt);
            }
        });

        BNTFIND.setBackground(new java.awt.Color(255, 153, 153));
        BNTFIND.setText("FIND");
        BNTFIND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNTFINDActionPerformed(evt);
            }
        });

        BNTOPEN.setBackground(new java.awt.Color(255, 153, 153));
        BNTOPEN.setText("OPEN");
        BNTOPEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNTOPENActionPerformed(evt);
            }
        });

        BNTEXIT.setBackground(new java.awt.Color(255, 153, 153));
        BNTEXIT.setText("EXIT");
        BNTEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNTEXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BNTDELETE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BNTFIND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BNTOPEN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BNTEXIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BNTDELETE)
                .addGap(18, 18, 18)
                .addComponent(BNTFIND)
                .addGap(18, 18, 18)
                .addComponent(BNTOPEN)
                .addGap(18, 18, 18)
                .addComponent(BNTEXIT)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("record: 1 or 5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))))
                            .addComponent(jLabel3))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextSALARY, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextYEAR_OLD, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel8)))
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(BNTSAVE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addComponent(BNTNEW, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(jLabeltime, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextSALARY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextYEAR_OLD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabeltime, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(BNTNEW)
                        .addGap(18, 18, 18)
                        .addComponent(BNTSAVE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void filltable() {
        mode.setRowCount(0);
        for (SinhVien i : SV) {
            Object sv[] = new Object[5];
            sv[0] = i.getMa();

            sv[1] = i.getHoten();

            sv[2] = i.getLuong();

            sv[3] = i.getEmail();

            sv[4] = i.getTuoi();

            mode.addRow(sv);

        }
        mode.fireTableDataChanged();
    }

    public void iniTable() {
        String[] sv = new String[]{"mã", "họ tên", "lương ", "email", "tuổi"};
        mode.setColumnIdentifiers(sv);
        SV.add(new SinhVien("001", "lê công quý", 9, "congquy@240101", 20));
        SV.add(new SinhVien("002", "lê đức thành", 15, "ducthanh@241201", 21));
        SV.add(new SinhVien("003", "lê hữu long", 10, "long@240701", 29));
        SV.add(new SinhVien("004", "lê quốc toàn", 9, "toan@240601", 17));
        SV.add(new SinhVien("005", "nguyễn việt hà", 25, "ha@240101", 29));
        filltable();
    }

    public void add() {
        SinhVien SV1 = new SinhVien();
        SV1.setHoten(jTextNAME.getText());
        SV1.setMa(jTextID.getText());
        SV1.setLuong(Double.parseDouble(jTextSALARY.getText()));
        SV1.setEmail(jTextEMAIL.getText());
        SV1.setTuoi(Integer.parseInt(jTextYEAR_OLD.getText()));
        SV.add(SV1);
    }
    private void jTextYEAR_OLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextYEAR_OLDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextYEAR_OLDActionPerformed

    private void jTextNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNAMEActionPerformed

    private void jTextEMAILActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEMAILActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEMAILActionPerformed

    private void BNTSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNTSAVEActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if (jTextID.getText().trim().length() <= 0) {
            

            sb.append("Mã không được để trống");
        }
      
        if (jTextNAME.getText().trim().length() <= 0) {
            sb.append("Tên không được để trống");
        }
        if (jTextYEAR_OLD.getText().isEmpty()) {
            sb.append("Tuổi không được để trống");
        }
        if (jTextEMAIL.getText().isEmpty()) {
            sb.append("email không được để trống");
        }
        if (jTextSALARY.getText().isEmpty()) {
            sb.append("Lương không được để trống");
        }
        if (sb.length() > 0) {
            JOptionPane.showConfirmDialog(rootPane, sb.toString(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (checkluong() == true && checkMail() == true) {
            add();
            filltable();
        } else {
            JOptionPane.showMessageDialog(null, "email hoặc lương không hợp lệ");
        }


    }//GEN-LAST:event_BNTSAVEActionPerformed

    public boolean checkMail() {
        String Email = "\\w+@\\w+\\.\\w+";
        if (!jTextEMAIL.getText().matches(Email)) {

            return false;
        } else {
            return true;
        }
    }

    private void BNTNEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNTNEWActionPerformed
        jTextID.setText("");
        jTextNAME.setText("");
        jTextYEAR_OLD.setText("");
        jTextEMAIL.setText("");
        jTextSALARY.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_BNTNEWActionPerformed
    public void reset() {
        jTextID.setText("");
        jTextNAME.setText("");
        jTextYEAR_OLD.setText("");
        jTextEMAIL.setText("");
        jTextSALARY.setText("");
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int D = jTable1.getSelectedRow();
        check(D);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabeltimeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabeltimeAncestorAdded
        TIME time = new TIME(jLabeltime);
        time.start();
        jLabeltime.setEnabled(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabeltimeAncestorAdded

    private void BNTEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNTEXITActionPerformed
        // TODO add your handling code here:
         
        savefile(); 
        System.exit(0); 

    }//GEN-LAST:event_BNTEXITActionPerformed

    private void BNTOPENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNTOPENActionPerformed
        openfile();
    }//GEN-LAST:event_BNTOPENActionPerformed

    private void BNTDELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNTDELETEActionPerformed
        // TODO add your handling code here:
        remode();
        filltable();
    }//GEN-LAST:event_BNTDELETEActionPerformed

    private void BNTFINDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNTFINDActionPerformed
        String sv;
        int i;
//        sv = JOptionPane.showInternalInpSVutDialog(null, "mời bạn nhập vào mã nhân viên");
        sv = JOptionPane.showInputDialog("mời bạn nhập vào mã nhân viên");
        for (i = 0; i < SV.size(); i++) {
            SinhVien sv1 = SV.get(i);
            if (sv1.Ma.equalsIgnoreCase(sv)) {
                JOptionPane.showMessageDialog(this, "Mã nhân viên đã tìm thấy", "thông báo", JOptionPane.INFORMATION_MESSAGE);
                check(SV.indexOf(sv1));
                int index = i;
                add();
                break;
            }
        }

        if (i == SV.size()) {

            JOptionPane.showMessageDialog(null, "NV không tìm thấy", "thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BNTFINDActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if (Index < SV.size() - 1) {
            Index++;
            check(Index);
        }


    }//GEN-LAST:event_jButton5ActionPerformed
    public void savefile() {

        try {
            FileOutputStream fileOutputStream = new FileOutputStream("D:\\ASM.txt");
            ObjectOutputStream os = new ObjectOutputStream(fileOutputStream);
            os.writeObject(SV);
            os.close();
        } catch (IOException ex) {
            System.out.println("eror" + ex);
        }
    }

    // nhìn này

    public void openfile() {
        FileInputStream fileInputStream = null;
        ObjectInputStream os = null;
        try {
            fileInputStream = new FileInputStream("D:\\ASM.txt");
            os = new ObjectInputStream(fileInputStream);
            SV = (List<SinhVien>) os.readObject();
            os.close();
            fileInputStream.close();
            filltable();
        } catch (FileNotFoundException ex) {
            System.out.println("error" + ex);
        } catch (IOException ex) {

        } catch (ClassNotFoundException ex) {

        }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (Index > 0) {
            Index = 0;
            check(Index);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (Index > 0) {
            Index--;
            check(Index);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Index = SV.size() - 1;
        check(Index);


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextSALARYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSALARYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSALARYActionPerformed
    public void check(int D) {
        jTextNAME.setText(SV.get(D).getHoten());

        jTextYEAR_OLD.setText(String.valueOf(SV.get(D).getTuoi()));
        jTextEMAIL.setText(SV.get(D).getEmail());
        jTextSALARY.setText(String.valueOf(SV.get(D).getLuong()));
        jTextID.setText(String.valueOf(SV.get(D).getMa()));
        jTable1.setRowSelectionInterval(D, D);
        jLabel8.setText(
                "Record " + String.valueOf(D + 1) + " of " + String.valueOf(SV.size()));
    }

    public boolean checkluong() throws HeadlessException {
        try {
            double luong = Double.parseDouble(jTextSALARY.getText());
            if (luong < 5) {
                return false;
            } else {
                return true;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nhập sai định dạng lương", "LỖI", JOptionPane.ERROR_MESSAGE);
            return false;
        }

    }

    public void remode() {
        int index = jTable1.getSelectedRow();
        SV.remove(index);
    }

    /**
     * @param args the command line argument
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new QLNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BNTDELETE;
    private javax.swing.JButton BNTEXIT;
    private javax.swing.JButton BNTFIND;
    private javax.swing.JButton BNTNEW;
    private javax.swing.JButton BNTOPEN;
    private javax.swing.JButton BNTSAVE;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabeltime;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextEMAIL;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextNAME;
    private javax.swing.JTextField jTextSALARY;
    private javax.swing.JTextField jTextYEAR_OLD;
    // End of variables declaration//GEN-END:variables

}
