/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ôntap;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JosCongQuy
 */
public class TGDD extends javax.swing.JFrame {

    private List<DienThoai> dienThoais = new ArrayList<>();
    private DefaultTableModel tableModel = new DefaultTableModel();
    private String[] DT = new String[]{"Tên", "hãng", "Giá"};

    /**
     * Creates new form TGDD
     */
    public TGDD() {
        initComponents();
        String[] DT = new String[]{"Tên", "hãng", "Giá"};
        tableModel.setColumnIdentifiers(DT);
        jTable1.setModel(tableModel);
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtname = new javax.swing.JTextField();
        txthang = new javax.swing.JTextField();
        txtgia = new javax.swing.JTextField();
        btnthem = new javax.swing.JButton();
        btnghi = new javax.swing.JButton();
        btnmo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("THẾ GIỚI DI ĐỘNG ");

        jLabel2.setText("TÊN");

        jLabel3.setText("HÃNG");

        jLabel4.setText("GIÁ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TÊN", "HÃNG", "GIÁ"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnthem.setText("THÊM");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnghi.setText("GHI");
        btnghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnghiActionPerformed(evt);
            }
        });

        btnmo.setText("MỞ");
        btnmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(txthang)
                    .addComponent(txtgia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnghi)
                    .addComponent(btnthem)
                    .addComponent(btnmo))
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnthem)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txthang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnghi))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnmo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        StringBuilder ss = new StringBuilder();
        if (txtname.getText().isEmpty()) {
            ss.append("tên không được để trông\n");
        }
        if (txtgia.getText().isEmpty()) {
            ss.append("Giá khoogn dc để trống");
        }
        if (ss.length() > 0) {
            JOptionPane.showMessageDialog(null, ss.toString(), "lỗi", JOptionPane.NO_OPTION);
        }
        add();
        filltable();
        txtname.setText("");
        txtgia.setText("");
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnghiActionPerformed
        // TODO add your handling code here:
        ghi();
    }//GEN-LAST:event_btnghiActionPerformed

    private void btnmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoActionPerformed
        // TODO add your handling code here:
        open();
    }//GEN-LAST:event_btnmoActionPerformed

    /**
     * @param args the command line arguments
     */
    public void filltable() {
        tableModel.setRowCount(0);
        for (DienThoai DT : dienThoais) {
            Object[] ss = new Object[3];
            ss[0] = DT.getTen();
            ss[1] = DT.getHang();
            ss[2] = DT.getGia();
            tableModel.addRow(ss);
        }
        tableModel.fireTableDataChanged();
    }

    public void add() {
        DienThoai ss = new DienThoai();
        ss.setTen(txtname.getText());
        ss.setHang(txthang.getText());
        ss.setGia(Double.parseDouble(txtgia.getText()));
        dienThoais.add(ss);
    }

    public void ghi() {
        try {
            FileOutputStream fileOutputStream = new FileOutputStream("D:\\thithu.txt");
            ObjectOutputStream os = new ObjectOutputStream(fileOutputStream);
            os.writeObject(dienThoais);
            os.close();
            
            JOptionPane.showMessageDialog(null, "ghi file thành công", "thành công", JOptionPane.NO_OPTION);
            tableModel.setRowCount(0);
            tableModel.fireTableDataChanged();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TGDD.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "khong tim thay file", "that bai", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            Logger.getLogger(TGDD.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "ghi file that bai", "that bai", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void open() {
        FileInputStream fileInputStream = null;
        ObjectInputStream os = null;
        try {
            fileInputStream = new FileInputStream("D:\\thithu.txt");
            os = new ObjectInputStream(fileInputStream);
            dienThoais = (List<DienThoai>) os.readObject();
            os.close();
            fileInputStream.close();
            filltable();
        } catch (Exception ex) {
            Logger.getLogger(TGDD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TGDD.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TGDD.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TGDD.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TGDD.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TGDD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnghi;
    private javax.swing.JButton btnmo;
    private javax.swing.JButton btnthem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtgia;
    private javax.swing.JTextField txthang;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
